INSERT INTO EMP(FIRSTNAME, LASTNAME, MAIL, PASSWORD, ROLE) VALUES ('Admin', ' ', 'admin@alphasolutions.com', '1234', 'ADMIN');

INSERT INTO ROLE(NAME) VALUES ('ADMIN');
INSERT INTO ROLE(NAME) VALUES ('PROJECT_LEADER');
INSERT INTO ROLE(NAME) VALUES ('EMPLOYEE');