CREATE DATABASE IF NOT EXISTS ALPHASOLUTIONSDB DEFAULT CHARACTER SET utf8;
USE ALPHASOLUTIONSDB;

DROP TABLE IF EXISTS EMP_TASK;
DROP TABLE IF EXISTS EMP_ROLE;
DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS SUBPROJECT_TASKS;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS PROJECT_SUBPROJECTS;
DROP TABLE IF EXISTS SUBPROJECT;
DROP TABLE IF EXISTS PROJECT;

CREATE TABLE EMP(
EMPID INTEGER NOT NULL AUTO_INCREMENT, 
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
MAIL VARCHAR(70) UNIQUE NOT NULL, 
PASSWORD VARCHAR(50) NOT NULL,
ROLE VARCHAR(50),
PRIMARY KEY (EMPID)
);

CREATE TABLE ROLE(
ROLEID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50),
PRIMARY KEY (ROLEID)
);

CREATE TABLE PROJECT(
PROJECTID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(200),
STARTDATE DATETIME,
ENDDATE DATETIME,
TIMEEST INTEGER,
USEDTIME INTEGER,
PRIMARY KEY (PROJECTID)
);

CREATE TABLE SUBPROJECT(
SUBPROJECTID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(200),
STARTDATE DATETIME,
ENDDATE DATETIME,
TIMEEST INTEGER,
PROJECTID INTEGER,
PRIMARY KEY (SUBPROJECTID),
FOREIGN KEY (PROJECTID) REFERENCES PROJECT(PROJECTID)
);

CREATE TABLE TASK(
TASKID INTEGER NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(200),
STARTDATE DATETIME,
ENDDATE DATETIME,
TIMEEST INTEGER DEFAULT 0,
SUBPROJECTID INTEGER,
USEDTIME INTEGER DEFAULT 0,
PRIMARY KEY (TASKID),
FOREIGN KEY (SUBPROJECTID) REFERENCES SUBPROJECT(SUBPROJECTID)
);

CREATE TABLE EMP_TASK(
EMPID INTEGER NOT NULL,
TASKID INTEGER NOT NULL,
FOREIGN KEY (EMPID) REFERENCES EMP(EMPID),
FOREIGN KEY (TASKID) REFERENCES TASK(TASKID)
);

CREATE TABLE PROJECT_SUBPROJECTS(
SUBPROJECTID INTEGER NOT NULL,
PROJECTID INTEGER NOT NULL,
FOREIGN KEY (SUBPROJECTID) REFERENCES SUBPROJECT(SUBPROJECTID),
FOREIGN KEY (PROJECTID) REFERENCES PROJECT(PROJECTID)
);

CREATE TABLE SUBPROJECT_TASKS(
TASKID INTEGER NOT NULL, 
SUBPROJECTID INTEGER NOT NULL,
FOREIGN KEY (TASKID) REFERENCES TASK(TASKID),
FOREIGN KEY (SUBPROJECTID) REFERENCES SUBPROJECT(SUBPROJECTID)
);
